#!/bin/bash

key_file="~/.ssh/id_ed25519"

echo Create ssh key at a remote PC

echo Preparing for creating ssh key
echo Remote host name for ssh connect
echo It may be user@addres or just host name from local ssh config
echo Here is config file ~/.ssh/config
cat ~/.ssh/config
echo Enter the remote host name:
read hostname
echo $hostname

echo key file is $key_file
echo Enter email for key file:
read email
echo push any key to create the keyfile: $key_file at $hostname with email: $email
read anykey
echo Connecting to remote host: $hostname

ssh $hostname << EOF

echo We are inside the remote host: $hostname
echo Generating SSH keys....

ssh-keygen -t ed25519 -f $key_file -C $email -N ""


echo $key_file public key: 

cat $key_file.pub
EOF

echo Returned to the local host!
